filter:
    excluded_paths:
        - vendor/*
        - Tests/*

checks:
    php:
        code_rating: true
        duplication: true

build:
    environment:
        mongodb: '3.6'
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        coverage:
            tests:
                override:
                    -
                        command: './bin/phpunit --coverage-clover clover.xml'
                        coverage:
                            file: 'clover.xml'
                            format: 'clover'
