monolog:
    handlers:
        main:
            type: fingers_crossed
            handler: grouped
        grouped:
            type: group
            members: [streamed, errors]
        streamed:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
        errors:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%_errors.log'
            level: warning
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
